### ISSUE TITLE
unitTestForBg5 getBottleMessage in iOS gives error:

### ISSUE THREAD

**Issue by ihealthdavid** [iHealthLab/plugin-ihealth-bg#2]
@wushuang2012 
unitTestForBg5 in iOS gives error:
2015-08-23 02:42:30.563 meteor_ihealth_bg1530:477423 date
2015-08-23 02:42:30.565 meteor_ihealth_bg[1530:477423] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: expiretime)'
*** First throw call stack:
(0x2b5780d7 0x39cf7c77 0x2b493385 0x523c3 0x116b31 0x2b52fea5 0x2b4899ed 0x2c1ed3a1 0xc3e15 0x11e0cd 0xc241d 0x11c7bd 0xf39f9 0xf47ab 0x2c1de187 0x2b53e00f 0x2b53d423 0x2b53baa1 0x2b4876d1 0x2b4874e3 0x32e231a9 0x2ec39445 0x25973 0x3a2c5aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

https://github.com/iHealthLab/test-labs/blob/master/unitTestForBg5/unitTestForBg5.js#L102-L115

**Comment by ihealthdavid** [comment]
Closing. Duplicate of #4

**Comment by wushuang2012** [comment]
I've already finished modification
